config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  resources :rooms, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end
  
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebrtcApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<h1>Rooms</h1>
<ul>
  <% @rooms.each do |room| %>
    <li><%= link_to room.name, room_path(room) %></li>
  <% end %>
</ul>

<%= link_to 'Create New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>Create a New Room</h1>

<%= form_with model: @room, local: true do |form| %>
  <div>
    <%= form.label :name, "Room Name" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit "Create Room" %>
  </div>
<% end %>

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>
<div id="video-container">
  <video id="localVideo" autoplay></video>
  <video id="remoteVideo" autoplay></video>
</div>

<%= javascript_include_tag 'rooms' %>